.TH "PKG_SEARCH" "1" 
.SH "NAME" 
pkg_search - Blazing fast intuitive package search
.SH "SYNOPSIS" 
.PP 
\fBpkg_search\fP [\fBoptions\fP] 
.SH "DESCRIPTION" 
.PP 
\fBpkg_search\fP
is a blazing fast interactive OpenBSD package search with the ability to retrieve package metadata on demand.
.SH "OPTIONS" 
.IP "\fB-i | --info\fP " 10
retrieve metadata information of the selected package
.IP "\fB-h | --help\fP " 10
print help message and exit

.SH "AUTHOR" 
.PP
This manual page is written by The OpenBSD Guy <theopenbsdguy@gmail.com>, the main author of the pkg_search utility. Permission is granted to copy, distribute
and/or modify this document under the terms of the GNU GPL.
